e_hac/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from .views import add_ehac, ehac_list, getEhacs, getEhac, createEhac, updateEhac, deleteEhac

urlpatterns = [
    path('add-ehac', add_ehac, name='add_ehac'),
    path('ehac-list', ehac_list, name='ehac_list'),
    path('ehac_server/', getEhacs, name='getEhacs'),
    path('ehac_server/create/', createEhac, name='createEhac'),
    path('ehac_server/<str:pk>/', getEhac, name='getEhac'),
    path('ehac_server/update/<str:pk>/', updateEhac, name='updateEhac'),
    path('ehac_server/delete/<str:pk>/', deleteEhac, name='deleteEhac'),
]

form_pendaftaran/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.daftar_vaksin, name='register_vaksin'),
    path('update/', views.user_update_view, name='update_user'),
    path('ajax/load-tanggal/', views.load_tanggal, name='ajax_load_tanggal'), # AJAX
    path('ajax/load-jenis/', views.load_jenis, name='ajax_load_jenis')
]

uts_e02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplikasi_vaksin.urls')),
    path('', include('server.urls')),
    path('user/', include('user_regis_login.urls')),
    path('user/', include('admin_tambah_faskes.urls')),
    path('user/', include('form_pendaftaran.urls')),
    path('user/', include('Daftar_PCR.urls')),
    path('user/', include('e_hac.urls')),
    path('user/', include('user_profile.urls')),
]
"""
mungkin kalau yang berhubungan dengan user, awalan path bisa pakai 'user/' aja, biar sama gitu. misal path('user/' include('profile.urls')). yang penting di urls tiap app dibedakan gitu. misal path('dashboard/', dashboard, name='dashboard') untuk dashboard, path('self_assesment/', self_assesment, name='self_assesment') untuk self_assesment, dst dalam app yang sama misal profile
"""

Daftar_PCR/models.py
from django.db import models

# Create your models here.
class data_PCR(models.Model):
    email = models.EmailField(blank=True, default="a@a.com")
    lokasi = models.CharField(max_length=60)
    waktu = models.CharField(max_length=60)

aplikasi_vaksin/models.py
from django.db import models
from admin_tambah_faskes.models import Lokasi, TanggalWaktu, JenisVaksin
# Create your models here.
class User(models.Model):
    email = models.EmailField()
    password = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    no_hp = models.CharField(max_length=12)
    usia = models.CharField(max_length=3, blank=True, default="-")
    nik = models.CharField(max_length=15, blank=True, default="-")
    domisili = models.CharField(max_length=50, blank=True, default="-")
    lokasi = models.ForeignKey(Lokasi, on_delete=models.SET_NULL, blank=True, null=True)
    tanggal = models.ForeignKey(TanggalWaktu, on_delete=models.SET_NULL, blank=True, null=True)
    jenis = models.ForeignKey(JenisVaksin, on_delete=models.SET_NULL, blank=True, null=True)
    def __str__(self) -> str:
        return f"{self.name} | {self.email}"
        
        

form_pendaftaran/models.py
from django.db import models

form_pendaftaran/forms.py
import urllib
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from django.forms.widgets import TextInput, Textarea
from aplikasi_vaksin.models import User
from django.http import QueryDict
from django.forms.models import model_to_dict
from admin_tambah_faskes.models import Lokasi, TanggalWaktu, JenisVaksin

class DaftarVaksin(forms.ModelForm):
  """Form definition for Note."""

  class Meta:
    """Meta definition for Noteform."""
    model = User
    fields = ('email', 'password', 'name', 'no_hp', 'usia', 'nik', 'domisili','lokasi','tanggal', 'jenis')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tanggal'].queryset = TanggalWaktu.objects.none()

        if 'lokasi' in self.data:
            try:
                lokasi_id = int(self.data.get('lokasi'))
                self.fields['tanggal'].queryset = TanggalWaktu.objects.filter(lokasi_id=lokasi_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['tanggal'].queryset = self.instance.lokasi.tanggal_set.order_by('name')
    
    
        self.fields['jenis'].queryset = JenisVaksin.objects.none()
        if 'tanggal' in self.data:
            try:
                tanggal_id = int(self.data.get('tanggal'))
                self.fields['jenis'].queryset = JenisVaksin.objects.filter(tanggal_id=tanggal_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['jenis'].queryset = self.instance.tanggal.jenis_set.order_by('name')
   
    # custom label
    labels = {
      'email' : 'Email',
      'password' : 'Password',
      'name' : 'Nama Lengkap',
      'no_hp' : 'No Handphone',
      'usia' : 'Usia',
      'nik' : 'NIK',
      'domisili' : 'Domisili',
      'lokasi' : 'Lokasi',
    }
    """
    ** custom witdgets **
    attrs itu digunakan untuk mengatur atribut dari input yang kita gunakan. misal kita ingin tag input kita seperti ini 
    <input id='id_input' placeholder='input' type='text' >
    maka kita tinggal isi attrs dengan dictionary yang keynya adalah nam_atribut dan valuenya adalah value yang kita inginkan. Usahakan kita tidak salah memasukkan atribut dan valuenya biar tidak jadi error :D
    """
    widgets = {
      'email' : forms.TextInput(
        attrs={
          'type' : 'email',
          'placeholder' : 'Email',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
        }
      ),
      'password' : forms.TextInput(
        attrs={
          'type' : 'password',
          'placeholder' : 'Password',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
        }
      ),
      'name' : forms.TextInput(
        attrs={
          'type' : 'text',
          'placeholder' : 'Nama lengkap',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
        }
      ),
      'no_hp' : forms.TextInput(
        attrs={
          'type' : 'tel',
          'placeholder' : ' No handphone',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
        }
      ),
      'usia' : forms.TextInput(
        attrs={
          'type' : 'number',
          'min'  :'0',
          'max' :'150',
          'placeholder' : 'Usia',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
          'required': 'required',
        }
      ),
      'nik' : forms.TextInput(
        attrs={
          'type' : 'number',
          'placeholder' : 'NIK',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
          'required': 'required',
        }
      ),
      'domisili' : forms.TextInput(
        attrs={
          'type' : 'text',
          'placeholder' : 'Domisili',
          'class':'form-control',
          'aria-describedby':'inputGroupPrepend',
          'required': 'required',
        }
      ),
      'lokasi' : forms.Select()
    }
    

form_pendaftaran/views.py
from django.contrib.auth.models import User as DjangoUser
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse,response
from django.contrib import messages
import json
from aplikasi_vaksin.models import User
from admin_tambah_faskes.models import Lokasi, TanggalWaktu, JenisVaksin
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import DaftarVaksin
from aplikasi_vaksin.models import User
from json import dumps

#def getRoutes(request):
 # routes = [
   # {
    #  'Endpoint': 
   # }
#  ]
# Create your views here.
@login_required
def daftar_vaksin(request):
  # create object of form
  form_vaksin = DaftarVaksin(request.POST or None, request.FILES or None)
  users = User.objects.all().values()
  user_as_json = []
  for user in users:
    user_as_json.append({'email':user['email']})
    
  # check if form data is valid
  if form_vaksin.is_valid():
    # save the form data to model
    form_vaksin.save()
  context = {
    "forms": form_vaksin,
    'users' : users,
    'json': dumps(user_as_json),
    "icons" : [
      "user_regis/icon/email.png",
      "user_regis/icon/key.png",
      "user_regis/icon/person.png",
      "user_regis/icon/phone.png",
      "user_regis/icon/age.png",
      "user_regis/icon/id.png",
      "user_regis/icon/location.png",
      "user_regis/icon/lokasi.png",
      ]
  }
  if request.method == "POST":
    email = request.POST['email']
    password = request.POST['password']
    name = request.POST['name']
    user = DjangoUser.objects.create_user(email, email, password)
    user.first_name = name
    user.save()
    # redirect
    return redirect('user_login')
    # return HttpResponseRedirect("/lab-4")
  return render(request, "user_regis/index.html", context)

def user_update_view(request, pk):
    daftar = get_object_or_404(UserVaksin, pk=pk)
    form = DaftarVaksin(instance.initial(request.POST.copy()),instance=instance)
    if request.method == 'POST':
        form = DaftarVaksin(request.POST, instance=daftar)
        if form.is_valid():
            form.save()
            return redirect('update_user', pk=pk)
    return render(request, 'user_regis/index.html', {'form': form})

# AJAX
def load_tanggal(request):
    lokasi_id = request.GET.get('lokasi')
    dates = TanggalWaktu.objects.filter(lokasi_id=lokasi_id).all()
    return render(request, 'user_regis/tanggal_dropdown_list_options.html', {'dates': dates})

def load_jenis(request):
    tanggal_id = request.GET.get('tanggal')
    types = JenisVaksin.objects.filter(tanggal_id=tanggal_id).order_by('name')
    return render(request, 'user_regis/jenis_dropdown_list_options.html', {'types': types})

form_pendaftaran/templates/user_regis/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- <link rel="stylesheet" href="{% static 'user_regis/style.css' %}">
  -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
  <script src="https://kit.fontawesome.com/c30b5ee371.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'user_regis/new_style.css' %}">
  <title>Register</title>
</head>
<body>
  <!-- untuk mendapatkan data User-->
  <!-- Triknya biar tidak kelihatan di browser, properti css display dibuat jadi none -->
  <!-- {% for user in users %}
    <span class="emails">{{user.email}}</span>
    <span class="passwords">{{user.password}}</span>
  {% endfor %} -->
  <form method="POST" id="userForm" action="{% url 'register_vaksin' %}" data-tanggal-url="{% url 'ajax_load_tanggal' %}" class="needs-validation container"  novalidate>
    <div class="logo">
      <h1>VaksinYuk</h1>
    </div>
    <h2>Register</h2>
    <div class="icons" style="display: none;">
      {% for form in forms %}
        <label class="icon" for='{{form.id_for_label}}'></label>
        <!-- <img class="icon" src="{% static icon %}" srcset=""> -->
      {% endfor %}
    </div>
    <!-- <h6 id="email_message">Email anda valid</h6>
    <h6 id="password_message">Maaf password tidak sesuai</h6> -->
    <h6 id="checkbox_message"></h6>
    {% csrf_token %}
    {% for form in forms %}
    <div class="col">
      <label for="{{form.id_for_label}}" class="form-label">{{form.label}} </label>
      <div class="input-group has-validation" >
        <span class="input-group-text" id="inputGroupPrepend" style="border-radius: 10px 0 0 10px;"><label for="{{form.id_for_label}}" ><div id="label_{{form.id_for_label}}"></div></label>
        </span>
        <!-- <span class="input-group-text" id="inputGroupPrepend" style="border-radius: 10px 0 0 10px;"><label for="{{form.id_for_label}}" ><i class="bi bi-envelope-open"></i></label>
        </span> -->
        <!-- <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" placeholder="Email" style="border-radius: 0 10px 10px 0;" required> -->
        {{form}}
        
        {% if form.label == "Password" %}
          <div id="password-eye" style="position: absolute; top: 7px; right: 30px; z-index: 1000; "><i class="bi bi-eye-slash-fill"></i></div>
        {% endif %}
          
        <div class="invalid-feedback">
          {% if form.label == 'Email' %}
            Email anda tidak valid
          {% else %}
            Entri ini tidak boleh kosong
          {% endif %}
        </div>
      </div>
    </div>
      <!-- <label for='{{form.id_for_label}}' >{{form.label}} </label>
      {{form}} -->
    {% endfor %}
   <div class="form-group options">
     <h4>Silakan Isi Form Assesment</h4>
     <h6>Anda harus memenuhi persyaratan di bawah ini untuk dapat menerima vaksin</h6>
      <span class="checkbox payment-radio">
        <label class = "check1"><input class ="checkboxes" type="checkbox" name="type[]" value="A" required />Selama 14 hari terakhir, saya tidak memiliki kontak dengan pasien COVID-19.</label>
      </span>
      <span class="checkbox payment-radio">
        <label class = "check1"><input class ="checkboxes" type="checkbox" name="type[]" value="B" required />Saya tidak terjangkit COVID-19 dalam 14 hari terakhir.</label>
      </span>
      <span class="checkbox payment-radio">
        <label class = "check1"><input class ="checkboxes" type="checkbox" name="type[]" value="C" required />Saya tidak memiliki penyakit kronis dan/atau sedang hamil.</label>
      </span>
      <span class="checkbox payment-radio">
        <label class = "check1"><input class ="checkboxes" type="checkbox" name="type[]" value="D" required />Saya tidak memiliki alergi yang tidak diketahui.</label>
      </span>
    </div>
    <button type="submit"><span>Kirim</span></button>
    <h5>Jika anda sudah mempunyai akun, silahkan <a href="/user/login">login</a></h5>
  </form>
  <br><br><br>
  <script type="text/javascript">
    let json = JSON.parse("{{json|escapejs}}");
  </script>
  <script src="{% static 'jquery/jquery.js' %}"></script>
  <script src="{% static 'user_regis/script.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  <script src="{% static 'user_regis/new_script.js' %}"></script>
<script>
  $("#id_lokasi").change(function () {
    const url = $("#userForm").attr("data-tanggal-url");  // get the url of the `load_cities` view
        const lokasiId = $(this).val();  // get the selected lokasi ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: "{% url 'ajax_load_tanggal' %}",            // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'lokasi': lokasiId       // add the lokasi id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_tanggal").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
	$("#id_tanggal").change(function () {
        const url = $("#userForm").attr("data-jenis-url");  // get the url of the `load_cities` view
        const tanggalId = $(this).val();  // get the selected lokasi ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: "{% url 'ajax_load_jenis' %}",                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                 'tanggal': tanggalId      // add the lokasi id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_jenis").html(data);  // replace the contents of the tanggal input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (tanggal) {
                    html_data += `<option value="${tanggal.id}">${tanggal.name}</option>`
                });
                console.log(html_data);
                $("#id_tanggal").html(html_data);

                */
            }
        });

    });
</script>
</body>
</html>

form_pendaftaran/templates/user_regis/jenis_dropdown_list_options.html
<option value="">---------</option>
{% for type in types %}
<option value="{{ type.pk }}">{{ type.name }}</option>
{% endfor %}

form_pendaftaran/templates/user_regis/tanggal_dropdown_list_options.html
<option value="">---------</option>
{% for i in dates %}
<option value="{{ i.pk }}">{{ i.name }}</option>
{% endfor %}